name: Crystal CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Check format
        run: crystal tool format --check
  check_ameba:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Check ameba
        run: ./bin/ameba
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    runs-on: ubuntu-20.04
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Build dependencies
        run: cd ext && make && cd -
      - name: Run tests
        run: crystal spec
